/*
 * Generated by JasperReports - 15-11-13 12:04 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class ordenCompraLocal_1384531494600_176120 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_solicitante = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_bs = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_sw_cargos_extra = null;
    private JRFillParameter parameter_sus = null;
    private JRFillParameter parameter_nulo = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_cod_personal1 = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_logo = null;
    private JRFillParameter parameter_cod_personal2 = null;
    private JRFillParameter parameter_aprobado1 = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_texto = null;
    private JRFillParameter parameter_cod_personal3 = null;
    private JRFillParameter parameter_aprobado2 = null;
    private JRFillParameter parameter_aprobado3 = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_fecha3 = null;
    private JRFillParameter parameter_fecha2 = null;
    private JRFillParameter parameter_total_detalle = null;
    private JRFillParameter parameter_fecha1 = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_titulo = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_fechaEntrega = null;
    private JRFillParameter parameter_cargo3 = null;
    private JRFillParameter parameter_cargo2 = null;
    private JRFillParameter parameter_codOrdenCompra = null;
    private JRFillParameter parameter_cargo1 = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_MATERIALES_NOMBRE_COMERCIAL_MATERIAL = null;
    private JRFillField field_CONTACTOS_PROVEEDOR_AP_MATERNO_CONTACTO = null;
    private JRFillField field_ALMACENES_OBS_ALMACEN = null;
    private JRFillField field_UNIDADES_MEDIDA_NOMBRE_UNIDAD_MEDIDA = null;
    private JRFillField field_CONTACTOS_PROVEEDOR_AP_PATERNO_CONTACTO = null;
    private JRFillField field_ORDENES_COMPRA_DIAS_TERMINOSPAGO = null;
    private JRFillField field_ORDENES_COMPRA_OBS_ORDEN_COMPRA_APROBACION = null;
    private JRFillField field_PROVEEDORES_CIUDAD_PROVEEDOR = null;
    private JRFillField field_ORDENES_COMPRA_OBS_ORDEN_COMPRA = null;
    private JRFillField field_ORDENES_COMPRA_EMITIR_CHEQUEANOMBREDE = null;
    private JRFillField field_ORDENES_COMPRA_FECHA_ENTREGA = null;
    private JRFillField field_MEDIOS_PAGO_NOMBRE_MEDIOPAGO = null;
    private JRFillField field_ORDENES_COMPRA_DETALLE_DESCRIPCION = null;
    private JRFillField field_ORDENES_COMPRA_DETALLE_PRECIO_TOTAL = null;
    private JRFillField field_ORDENES_COMPRA_DIVISION = null;
    private JRFillField field_PROVEEDORES_TELEFONO_PROVEEDOR = null;
    private JRFillField field_ORDENES_COMPRA_FECHA_EMISION = null;
    private JRFillField field_PROVEEDORES_NOMBRE_PROVEEDOR = null;
    private JRFillField field_PROVEEDORES_EMAIL_PROVEEDOR = null;
    private JRFillField field_PROVEEDORES_OBS_PROVEEDOR = null;
    private JRFillField field_ORDENES_COMPRA_FECHA_DESPACHO = null;
    private JRFillField field_PROVEEDORES_FAX_PROVEEDOR = null;
    private JRFillField field_ORDENES_COMPRA_NRO_ORDEN_COMPRA = null;
    private JRFillField field_ORDENES_COMPRA_DETALLE_PRECIO_UNITARIO = null;
    private JRFillField field_UNIDADES_MEDIDA_ABREVIATURA = null;
    private JRFillField field_GRADOS_ACADEMICOS_ABREVIATURA_GRADO_ACADEMICO = null;
    private JRFillField field_ALMACENES_NOMBRE_ALMACEN = null;
    private JRFillField field_PERSONAL_NOMBRE_PILA = null;
    private JRFillField field_PLAN_DE_CUENTAS_NOMBRE_CUENTA = null;
    private JRFillField field_ORDENES_COMPRA_DETALLE_CANTIDAD_NETA = null;
    private JRFillField field_TIPOS_DOCUMENTOS_COMPRAS_NOMBRE_TIPO_DOCUMENTO = null;
    private JRFillField field_PROVEEDORES_PAGINAWEB_PROVEEDOR = null;
    private JRFillField field_CONTACTOS_PROVEEDOR_CARGO_CONTACTO = null;
    private JRFillField field_PERSONAL_AP_PATERNO_PERSONAL = null;
    private JRFillField field_CONTACTOS_PROVEEDOR_NOMBRE_CONTACTO = null;
    private JRFillField field_TIPOS_CENTRO_DE_COSTO_NOMBRE_TIPO_CENTRO_COSTOS = null;
    private JRFillField field_DISTRIBUCION_GASTOS_COMPRAS_DEPARTAMENTO = null;
    private JRFillField field_PROVEEDORES_DIRECCION_PROVEEDOR = null;
    private JRFillField field_PAISES_NOMBRE_PAIS = null;
    private JRFillField field_PERSONAL_AP_MATERNO_PERSONAL = null;
    private JRFillField field_TIPOS_PAGO_NOMBRE_TIPO_PAGO = null;
    private JRFillField field_ORDENES_COMPRA_DESC_FECHA_ENTREGA = null;
    private JRFillField field_TIPOS_TRANSPORTE_NOMBRE_TIPO_TRANSPORTE = null;
    private JRFillField field_DISTRIBUCION_GASTOS_COMPRAS_PRODUCTOS = null;
    private JRFillField field_DISTRIBUCION_GASTOS_COMPRAS_REGIONAL = null;
    private JRFillField field_ORDENES_COMPRA_COD_ORDEN_COMPRA = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_totalLiteral_COUNT = null;
    private JRFillVariable variable_totalOC_COUNT = null;
    private JRFillVariable variable_cargosExtra_COUNT = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_solicitante = (JRFillParameter)pm.get("solicitante");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_bs = (JRFillParameter)pm.get("bs");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_sw_cargos_extra = (JRFillParameter)pm.get("sw_cargos_extra");
        parameter_sus = (JRFillParameter)pm.get("sus");
        parameter_nulo = (JRFillParameter)pm.get("nulo");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_cod_personal1 = (JRFillParameter)pm.get("cod_personal1");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_logo = (JRFillParameter)pm.get("logo");
        parameter_cod_personal2 = (JRFillParameter)pm.get("cod_personal2");
        parameter_aprobado1 = (JRFillParameter)pm.get("aprobado1");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_texto = (JRFillParameter)pm.get("texto");
        parameter_cod_personal3 = (JRFillParameter)pm.get("cod_personal3");
        parameter_aprobado2 = (JRFillParameter)pm.get("aprobado2");
        parameter_aprobado3 = (JRFillParameter)pm.get("aprobado3");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_fecha3 = (JRFillParameter)pm.get("fecha3");
        parameter_fecha2 = (JRFillParameter)pm.get("fecha2");
        parameter_total_detalle = (JRFillParameter)pm.get("total_detalle");
        parameter_fecha1 = (JRFillParameter)pm.get("fecha1");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_titulo = (JRFillParameter)pm.get("titulo");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_fechaEntrega = (JRFillParameter)pm.get("fechaEntrega");
        parameter_cargo3 = (JRFillParameter)pm.get("cargo3");
        parameter_cargo2 = (JRFillParameter)pm.get("cargo2");
        parameter_codOrdenCompra = (JRFillParameter)pm.get("codOrdenCompra");
        parameter_cargo1 = (JRFillParameter)pm.get("cargo1");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_MATERIALES_NOMBRE_COMERCIAL_MATERIAL = (JRFillField)fm.get("MATERIALES_NOMBRE_COMERCIAL_MATERIAL");
        field_CONTACTOS_PROVEEDOR_AP_MATERNO_CONTACTO = (JRFillField)fm.get("CONTACTOS_PROVEEDOR_AP_MATERNO_CONTACTO");
        field_ALMACENES_OBS_ALMACEN = (JRFillField)fm.get("ALMACENES_OBS_ALMACEN");
        field_UNIDADES_MEDIDA_NOMBRE_UNIDAD_MEDIDA = (JRFillField)fm.get("UNIDADES_MEDIDA_NOMBRE_UNIDAD_MEDIDA");
        field_CONTACTOS_PROVEEDOR_AP_PATERNO_CONTACTO = (JRFillField)fm.get("CONTACTOS_PROVEEDOR_AP_PATERNO_CONTACTO");
        field_ORDENES_COMPRA_DIAS_TERMINOSPAGO = (JRFillField)fm.get("ORDENES_COMPRA_DIAS_TERMINOSPAGO");
        field_ORDENES_COMPRA_OBS_ORDEN_COMPRA_APROBACION = (JRFillField)fm.get("ORDENES_COMPRA_OBS_ORDEN_COMPRA_APROBACION");
        field_PROVEEDORES_CIUDAD_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_CIUDAD_PROVEEDOR");
        field_ORDENES_COMPRA_OBS_ORDEN_COMPRA = (JRFillField)fm.get("ORDENES_COMPRA_OBS_ORDEN_COMPRA");
        field_ORDENES_COMPRA_EMITIR_CHEQUEANOMBREDE = (JRFillField)fm.get("ORDENES_COMPRA_EMITIR_CHEQUEANOMBREDE");
        field_ORDENES_COMPRA_FECHA_ENTREGA = (JRFillField)fm.get("ORDENES_COMPRA_FECHA_ENTREGA");
        field_MEDIOS_PAGO_NOMBRE_MEDIOPAGO = (JRFillField)fm.get("MEDIOS_PAGO_NOMBRE_MEDIOPAGO");
        field_ORDENES_COMPRA_DETALLE_DESCRIPCION = (JRFillField)fm.get("ORDENES_COMPRA_DETALLE_DESCRIPCION");
        field_ORDENES_COMPRA_DETALLE_PRECIO_TOTAL = (JRFillField)fm.get("ORDENES_COMPRA_DETALLE_PRECIO_TOTAL");
        field_ORDENES_COMPRA_DIVISION = (JRFillField)fm.get("ORDENES_COMPRA_DIVISION");
        field_PROVEEDORES_TELEFONO_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_TELEFONO_PROVEEDOR");
        field_ORDENES_COMPRA_FECHA_EMISION = (JRFillField)fm.get("ORDENES_COMPRA_FECHA_EMISION");
        field_PROVEEDORES_NOMBRE_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_NOMBRE_PROVEEDOR");
        field_PROVEEDORES_EMAIL_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_EMAIL_PROVEEDOR");
        field_PROVEEDORES_OBS_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_OBS_PROVEEDOR");
        field_ORDENES_COMPRA_FECHA_DESPACHO = (JRFillField)fm.get("ORDENES_COMPRA_FECHA_DESPACHO");
        field_PROVEEDORES_FAX_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_FAX_PROVEEDOR");
        field_ORDENES_COMPRA_NRO_ORDEN_COMPRA = (JRFillField)fm.get("ORDENES_COMPRA_NRO_ORDEN_COMPRA");
        field_ORDENES_COMPRA_DETALLE_PRECIO_UNITARIO = (JRFillField)fm.get("ORDENES_COMPRA_DETALLE_PRECIO_UNITARIO");
        field_UNIDADES_MEDIDA_ABREVIATURA = (JRFillField)fm.get("UNIDADES_MEDIDA_ABREVIATURA");
        field_GRADOS_ACADEMICOS_ABREVIATURA_GRADO_ACADEMICO = (JRFillField)fm.get("GRADOS_ACADEMICOS_ABREVIATURA_GRADO_ACADEMICO");
        field_ALMACENES_NOMBRE_ALMACEN = (JRFillField)fm.get("ALMACENES_NOMBRE_ALMACEN");
        field_PERSONAL_NOMBRE_PILA = (JRFillField)fm.get("PERSONAL_NOMBRE_PILA");
        field_PLAN_DE_CUENTAS_NOMBRE_CUENTA = (JRFillField)fm.get("PLAN_DE_CUENTAS_NOMBRE_CUENTA");
        field_ORDENES_COMPRA_DETALLE_CANTIDAD_NETA = (JRFillField)fm.get("ORDENES_COMPRA_DETALLE_CANTIDAD_NETA");
        field_TIPOS_DOCUMENTOS_COMPRAS_NOMBRE_TIPO_DOCUMENTO = (JRFillField)fm.get("TIPOS_DOCUMENTOS_COMPRAS_NOMBRE_TIPO_DOCUMENTO");
        field_PROVEEDORES_PAGINAWEB_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_PAGINAWEB_PROVEEDOR");
        field_CONTACTOS_PROVEEDOR_CARGO_CONTACTO = (JRFillField)fm.get("CONTACTOS_PROVEEDOR_CARGO_CONTACTO");
        field_PERSONAL_AP_PATERNO_PERSONAL = (JRFillField)fm.get("PERSONAL_AP_PATERNO_PERSONAL");
        field_CONTACTOS_PROVEEDOR_NOMBRE_CONTACTO = (JRFillField)fm.get("CONTACTOS_PROVEEDOR_NOMBRE_CONTACTO");
        field_TIPOS_CENTRO_DE_COSTO_NOMBRE_TIPO_CENTRO_COSTOS = (JRFillField)fm.get("TIPOS_CENTRO_DE_COSTO_NOMBRE_TIPO_CENTRO_COSTOS");
        field_DISTRIBUCION_GASTOS_COMPRAS_DEPARTAMENTO = (JRFillField)fm.get("DISTRIBUCION_GASTOS_COMPRAS_DEPARTAMENTO");
        field_PROVEEDORES_DIRECCION_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_DIRECCION_PROVEEDOR");
        field_PAISES_NOMBRE_PAIS = (JRFillField)fm.get("PAISES_NOMBRE_PAIS");
        field_PERSONAL_AP_MATERNO_PERSONAL = (JRFillField)fm.get("PERSONAL_AP_MATERNO_PERSONAL");
        field_TIPOS_PAGO_NOMBRE_TIPO_PAGO = (JRFillField)fm.get("TIPOS_PAGO_NOMBRE_TIPO_PAGO");
        field_ORDENES_COMPRA_DESC_FECHA_ENTREGA = (JRFillField)fm.get("ORDENES_COMPRA_DESC_FECHA_ENTREGA");
        field_TIPOS_TRANSPORTE_NOMBRE_TIPO_TRANSPORTE = (JRFillField)fm.get("TIPOS_TRANSPORTE_NOMBRE_TIPO_TRANSPORTE");
        field_DISTRIBUCION_GASTOS_COMPRAS_PRODUCTOS = (JRFillField)fm.get("DISTRIBUCION_GASTOS_COMPRAS_PRODUCTOS");
        field_DISTRIBUCION_GASTOS_COMPRAS_REGIONAL = (JRFillField)fm.get("DISTRIBUCION_GASTOS_COMPRAS_REGIONAL");
        field_ORDENES_COMPRA_COD_ORDEN_COMPRA = (JRFillField)fm.get("ORDENES_COMPRA_COD_ORDEN_COMPRA");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_totalLiteral_COUNT = (JRFillVariable)vm.get("totalLiteral_COUNT");
        variable_totalOC_COUNT = (JRFillVariable)vm.get("totalOC_COUNT");
        variable_cargosExtra_COUNT = (JRFillVariable)vm.get("cargosExtra_COUNT");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("C:\\ULTIMOS REPORTES WILMER\\jrxml\\25 MAYO 2010\\");
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 16)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 17)
        {
            value = (java.lang.Object)(((java.lang.String)parameter_nulo.getValue()));
        }
        else if (id == 18)
        {
            value = (java.lang.Object)(((java.lang.Double)parameter_total_detalle.getValue()));
        }
        else if (id == 19)
        {
            value = (java.lang.Object)(((java.lang.Integer)field_ORDENES_COMPRA_COD_ORDEN_COMPRA.getValue()));
        }
        else if (id == 20)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 21)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "cuotasOC.jasper");
        }
        else if (id == 22)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 23)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 24)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 25)
        {
            value = (java.lang.String)(((java.lang.String)parameter_texto.getValue()));
        }
        else if (id == 26)
        {
            value = (java.lang.Double)(((java.lang.Double)parameter_sus.getValue()));
        }
        else if (id == 27)
        {
            value = (java.lang.Double)(((java.lang.Double)parameter_bs.getValue()));
        }
        else if (id == 28)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 29)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 30)
        {
            value = (java.lang.Object)(((java.lang.String)parameter_nulo.getValue()));
        }
        else if (id == 31)
        {
            value = (java.lang.Object)(((java.lang.Double)parameter_total_detalle.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.Object)(((java.lang.Integer)field_ORDENES_COMPRA_COD_ORDEN_COMPRA.getValue()));
        }
        else if (id == 33)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 34)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "cargosExtraOC.jasper");
        }
        else if (id == 35)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 36)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 37)
        {
            value = (java.lang.String)(((java.lang.String)parameter_titulo.getValue()));
        }
        else if (id == 38)
        {
            value = (java.util.Date)(((java.sql.Timestamp)field_ORDENES_COMPRA_FECHA_EMISION.getValue()));
        }
        else if (id == 39)
        {
            value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_NRO_ORDEN_COMPRA.getValue()));
        }
        else if (id == 40)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_NOMBRE_PROVEEDOR.getValue()));
        }
        else if (id == 41)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_DIRECCION_PROVEEDOR.getValue()));
        }
        else if (id == 42)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_TELEFONO_PROVEEDOR.getValue()));
        }
        else if (id == 43)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_FAX_PROVEEDOR.getValue()));
        }
        else if (id == 44)
        {
            value = (java.lang.String)(((java.lang.String)field_CONTACTOS_PROVEEDOR_NOMBRE_CONTACTO.getValue())+" "+((java.lang.String)field_CONTACTOS_PROVEEDOR_AP_PATERNO_CONTACTO.getValue()));
        }
        else if (id == 45)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getValue())+ " de ");
        }
        else if (id == 46)
        {
            value = (java.lang.String)(""+((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
        }
        else if (id == 47)
        {
            value = (java.util.Date)(new Date());
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_CONTACTOS_PROVEEDOR_CARGO_CONTACTO.getValue()));
        }
        else if (id == 49)
        {
            value = (java.io.InputStream)(((java.io.InputStream)parameter_logo.getValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_CANTIDAD_NETA.getValue()));
        }
        else if (id == 51)
        {
            value = (java.lang.String)(((java.lang.String)field_UNIDADES_MEDIDA_ABREVIATURA.getValue()));
        }
        else if (id == 52)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_PRECIO_UNITARIO.getValue()));
        }
        else if (id == 53)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_PRECIO_TOTAL.getValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(((java.lang.String)field_MATERIALES_NOMBRE_COMERCIAL_MATERIAL.getValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_DETALLE_DESCRIPCION.getValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_PAGO_NOMBRE_TIPO_PAGO.getValue()));
        }
        else if (id == 57)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_CENTRO_DE_COSTO_NOMBRE_TIPO_CENTRO_COSTOS.getValue()));
        }
        else if (id == 58)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_DOCUMENTOS_COMPRAS_NOMBRE_TIPO_DOCUMENTO.getValue()));
        }
        else if (id == 59)
        {
            value = (java.lang.String)(((java.lang.String)field_PLAN_DE_CUENTAS_NOMBRE_CUENTA.getValue()));
        }
        else if (id == 60)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_OBS_ORDEN_COMPRA.getValue()));
        }
        else if (id == 61)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal1.getValue()));
        }
        else if (id == 62)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 63)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 64)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal2.getValue()));
        }
        else if (id == 65)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 66)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 67)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal3.getValue()));
        }
        else if (id == 68)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado1.getValue()));
        }
        else if (id == 71)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado2.getValue()));
        }
        else if (id == 72)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado3.getValue()));
        }
        else if (id == 73)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo1.getValue()));
        }
        else if (id == 74)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo2.getValue()));
        }
        else if (id == 75)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo3.getValue()));
        }
        else if (id == 76)
        {
            value = (java.lang.String)(((java.lang.String)parameter_solicitante.getValue()));
        }
        else if (id == 77)
        {
            value = (java.lang.String)(((java.lang.String)parameter_fechaEntrega.getValue()));
        }
        else if (id == 78)
        {
            value = (java.lang.String)(((java.lang.String)field_ALMACENES_NOMBRE_ALMACEN.getValue())+" "+((java.lang.String)field_ALMACENES_OBS_ALMACEN.getValue()));
        }
        else if (id == 79)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_EMITIR_CHEQUEANOMBREDE.getValue()));
        }
        else if (id == 80)
        {
            value = (java.lang.String)(((java.lang.String)field_MEDIOS_PAGO_NOMBRE_MEDIOPAGO.getValue()));
        }
        else if (id == 81)
        {
            value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_DIAS_TERMINOSPAGO.getValue()));
        }
        else if (id == 82)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_DEPARTAMENTO.getValue()));
        }
        else if (id == 83)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_REGIONAL.getValue()));
        }
        else if (id == 84)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_PRODUCTOS.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("C:\\ULTIMOS REPORTES WILMER\\jrxml\\25 MAYO 2010\\");
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 16)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 17)
        {
            value = (java.lang.Object)(((java.lang.String)parameter_nulo.getValue()));
        }
        else if (id == 18)
        {
            value = (java.lang.Object)(((java.lang.Double)parameter_total_detalle.getValue()));
        }
        else if (id == 19)
        {
            value = (java.lang.Object)(((java.lang.Integer)field_ORDENES_COMPRA_COD_ORDEN_COMPRA.getOldValue()));
        }
        else if (id == 20)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 21)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "cuotasOC.jasper");
        }
        else if (id == 22)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 23)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 24)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 25)
        {
            value = (java.lang.String)(((java.lang.String)parameter_texto.getValue()));
        }
        else if (id == 26)
        {
            value = (java.lang.Double)(((java.lang.Double)parameter_sus.getValue()));
        }
        else if (id == 27)
        {
            value = (java.lang.Double)(((java.lang.Double)parameter_bs.getValue()));
        }
        else if (id == 28)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 29)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 30)
        {
            value = (java.lang.Object)(((java.lang.String)parameter_nulo.getValue()));
        }
        else if (id == 31)
        {
            value = (java.lang.Object)(((java.lang.Double)parameter_total_detalle.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.Object)(((java.lang.Integer)field_ORDENES_COMPRA_COD_ORDEN_COMPRA.getOldValue()));
        }
        else if (id == 33)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 34)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "cargosExtraOC.jasper");
        }
        else if (id == 35)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 36)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 37)
        {
            value = (java.lang.String)(((java.lang.String)parameter_titulo.getValue()));
        }
        else if (id == 38)
        {
            value = (java.util.Date)(((java.sql.Timestamp)field_ORDENES_COMPRA_FECHA_EMISION.getOldValue()));
        }
        else if (id == 39)
        {
            value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_NRO_ORDEN_COMPRA.getOldValue()));
        }
        else if (id == 40)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_NOMBRE_PROVEEDOR.getOldValue()));
        }
        else if (id == 41)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_DIRECCION_PROVEEDOR.getOldValue()));
        }
        else if (id == 42)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_TELEFONO_PROVEEDOR.getOldValue()));
        }
        else if (id == 43)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_FAX_PROVEEDOR.getOldValue()));
        }
        else if (id == 44)
        {
            value = (java.lang.String)(((java.lang.String)field_CONTACTOS_PROVEEDOR_NOMBRE_CONTACTO.getOldValue())+" "+((java.lang.String)field_CONTACTOS_PROVEEDOR_AP_PATERNO_CONTACTO.getOldValue()));
        }
        else if (id == 45)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+ " de ");
        }
        else if (id == 46)
        {
            value = (java.lang.String)(""+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
        }
        else if (id == 47)
        {
            value = (java.util.Date)(new Date());
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_CONTACTOS_PROVEEDOR_CARGO_CONTACTO.getOldValue()));
        }
        else if (id == 49)
        {
            value = (java.io.InputStream)(((java.io.InputStream)parameter_logo.getValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_CANTIDAD_NETA.getOldValue()));
        }
        else if (id == 51)
        {
            value = (java.lang.String)(((java.lang.String)field_UNIDADES_MEDIDA_ABREVIATURA.getOldValue()));
        }
        else if (id == 52)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_PRECIO_UNITARIO.getOldValue()));
        }
        else if (id == 53)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_PRECIO_TOTAL.getOldValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(((java.lang.String)field_MATERIALES_NOMBRE_COMERCIAL_MATERIAL.getOldValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_DETALLE_DESCRIPCION.getOldValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_PAGO_NOMBRE_TIPO_PAGO.getOldValue()));
        }
        else if (id == 57)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_CENTRO_DE_COSTO_NOMBRE_TIPO_CENTRO_COSTOS.getOldValue()));
        }
        else if (id == 58)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_DOCUMENTOS_COMPRAS_NOMBRE_TIPO_DOCUMENTO.getOldValue()));
        }
        else if (id == 59)
        {
            value = (java.lang.String)(((java.lang.String)field_PLAN_DE_CUENTAS_NOMBRE_CUENTA.getOldValue()));
        }
        else if (id == 60)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_OBS_ORDEN_COMPRA.getOldValue()));
        }
        else if (id == 61)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal1.getValue()));
        }
        else if (id == 62)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 63)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 64)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal2.getValue()));
        }
        else if (id == 65)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 66)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 67)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal3.getValue()));
        }
        else if (id == 68)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado1.getValue()));
        }
        else if (id == 71)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado2.getValue()));
        }
        else if (id == 72)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado3.getValue()));
        }
        else if (id == 73)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo1.getValue()));
        }
        else if (id == 74)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo2.getValue()));
        }
        else if (id == 75)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo3.getValue()));
        }
        else if (id == 76)
        {
            value = (java.lang.String)(((java.lang.String)parameter_solicitante.getValue()));
        }
        else if (id == 77)
        {
            value = (java.lang.String)(((java.lang.String)parameter_fechaEntrega.getValue()));
        }
        else if (id == 78)
        {
            value = (java.lang.String)(((java.lang.String)field_ALMACENES_NOMBRE_ALMACEN.getOldValue())+" "+((java.lang.String)field_ALMACENES_OBS_ALMACEN.getOldValue()));
        }
        else if (id == 79)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_EMITIR_CHEQUEANOMBREDE.getOldValue()));
        }
        else if (id == 80)
        {
            value = (java.lang.String)(((java.lang.String)field_MEDIOS_PAGO_NOMBRE_MEDIOPAGO.getOldValue()));
        }
        else if (id == 81)
        {
            value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_DIAS_TERMINOSPAGO.getOldValue()));
        }
        else if (id == 82)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_DEPARTAMENTO.getOldValue()));
        }
        else if (id == 83)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_REGIONAL.getOldValue()));
        }
        else if (id == 84)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_PRODUCTOS.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("C:\\ULTIMOS REPORTES WILMER\\jrxml\\25 MAYO 2010\\");
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 16)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 17)
        {
            value = (java.lang.Object)(((java.lang.String)parameter_nulo.getValue()));
        }
        else if (id == 18)
        {
            value = (java.lang.Object)(((java.lang.Double)parameter_total_detalle.getValue()));
        }
        else if (id == 19)
        {
            value = (java.lang.Object)(((java.lang.Integer)field_ORDENES_COMPRA_COD_ORDEN_COMPRA.getValue()));
        }
        else if (id == 20)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 21)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "cuotasOC.jasper");
        }
        else if (id == 22)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 23)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 24)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 25)
        {
            value = (java.lang.String)(((java.lang.String)parameter_texto.getValue()));
        }
        else if (id == 26)
        {
            value = (java.lang.Double)(((java.lang.Double)parameter_sus.getValue()));
        }
        else if (id == 27)
        {
            value = (java.lang.Double)(((java.lang.Double)parameter_bs.getValue()));
        }
        else if (id == 28)
        {
            value = (java.lang.Object)(null);
        }
        else if (id == 29)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 30)
        {
            value = (java.lang.Object)(((java.lang.String)parameter_nulo.getValue()));
        }
        else if (id == 31)
        {
            value = (java.lang.Object)(((java.lang.Double)parameter_total_detalle.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.Object)(((java.lang.Integer)field_ORDENES_COMPRA_COD_ORDEN_COMPRA.getValue()));
        }
        else if (id == 33)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 34)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "cargosExtraOC.jasper");
        }
        else if (id == 35)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 36)
        {
            value = (java.lang.Boolean)(((java.lang.Integer)parameter_sw_cargos_extra.getValue())==1);
        }
        else if (id == 37)
        {
            value = (java.lang.String)(((java.lang.String)parameter_titulo.getValue()));
        }
        else if (id == 38)
        {
            value = (java.util.Date)(((java.sql.Timestamp)field_ORDENES_COMPRA_FECHA_EMISION.getValue()));
        }
        else if (id == 39)
        {
            value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_NRO_ORDEN_COMPRA.getValue()));
        }
        else if (id == 40)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_NOMBRE_PROVEEDOR.getValue()));
        }
        else if (id == 41)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_DIRECCION_PROVEEDOR.getValue()));
        }
        else if (id == 42)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_TELEFONO_PROVEEDOR.getValue()));
        }
        else if (id == 43)
        {
            value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_FAX_PROVEEDOR.getValue()));
        }
        else if (id == 44)
        {
            value = (java.lang.String)(((java.lang.String)field_CONTACTOS_PROVEEDOR_NOMBRE_CONTACTO.getValue())+" "+((java.lang.String)field_CONTACTOS_PROVEEDOR_AP_PATERNO_CONTACTO.getValue()));
        }
        else if (id == 45)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+ " de ");
        }
        else if (id == 46)
        {
            value = (java.lang.String)(""+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
        }
        else if (id == 47)
        {
            value = (java.util.Date)(new Date());
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_CONTACTOS_PROVEEDOR_CARGO_CONTACTO.getValue()));
        }
        else if (id == 49)
        {
            value = (java.io.InputStream)(((java.io.InputStream)parameter_logo.getValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_CANTIDAD_NETA.getValue()));
        }
        else if (id == 51)
        {
            value = (java.lang.String)(((java.lang.String)field_UNIDADES_MEDIDA_ABREVIATURA.getValue()));
        }
        else if (id == 52)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_PRECIO_UNITARIO.getValue()));
        }
        else if (id == 53)
        {
            value = (java.lang.Double)(((java.lang.Double)field_ORDENES_COMPRA_DETALLE_PRECIO_TOTAL.getValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(((java.lang.String)field_MATERIALES_NOMBRE_COMERCIAL_MATERIAL.getValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_DETALLE_DESCRIPCION.getValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_PAGO_NOMBRE_TIPO_PAGO.getValue()));
        }
        else if (id == 57)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_CENTRO_DE_COSTO_NOMBRE_TIPO_CENTRO_COSTOS.getValue()));
        }
        else if (id == 58)
        {
            value = (java.lang.String)(((java.lang.String)field_TIPOS_DOCUMENTOS_COMPRAS_NOMBRE_TIPO_DOCUMENTO.getValue()));
        }
        else if (id == 59)
        {
            value = (java.lang.String)(((java.lang.String)field_PLAN_DE_CUENTAS_NOMBRE_CUENTA.getValue()));
        }
        else if (id == 60)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_OBS_ORDEN_COMPRA.getValue()));
        }
        else if (id == 61)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal1.getValue()));
        }
        else if (id == 62)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 63)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 64)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal2.getValue()));
        }
        else if (id == 65)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 66)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 67)
        {
            value = (java.lang.Object)(((java.lang.Integer)parameter_cod_personal3.getValue()));
        }
        else if (id == 68)
        {
            value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "firma1.jasper");
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado1.getValue()));
        }
        else if (id == 71)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado2.getValue()));
        }
        else if (id == 72)
        {
            value = (java.lang.String)(((java.lang.String)parameter_aprobado3.getValue()));
        }
        else if (id == 73)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo1.getValue()));
        }
        else if (id == 74)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo2.getValue()));
        }
        else if (id == 75)
        {
            value = (java.lang.String)(((java.lang.String)parameter_cargo3.getValue()));
        }
        else if (id == 76)
        {
            value = (java.lang.String)(((java.lang.String)parameter_solicitante.getValue()));
        }
        else if (id == 77)
        {
            value = (java.lang.String)(((java.lang.String)parameter_fechaEntrega.getValue()));
        }
        else if (id == 78)
        {
            value = (java.lang.String)(((java.lang.String)field_ALMACENES_NOMBRE_ALMACEN.getValue())+" "+((java.lang.String)field_ALMACENES_OBS_ALMACEN.getValue()));
        }
        else if (id == 79)
        {
            value = (java.lang.String)(((java.lang.String)field_ORDENES_COMPRA_EMITIR_CHEQUEANOMBREDE.getValue()));
        }
        else if (id == 80)
        {
            value = (java.lang.String)(((java.lang.String)field_MEDIOS_PAGO_NOMBRE_MEDIOPAGO.getValue()));
        }
        else if (id == 81)
        {
            value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_DIAS_TERMINOSPAGO.getValue()));
        }
        else if (id == 82)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_DEPARTAMENTO.getValue()));
        }
        else if (id == 83)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_REGIONAL.getValue()));
        }
        else if (id == 84)
        {
            value = (java.lang.String)(((java.lang.String)field_DISTRIBUCION_GASTOS_COMPRAS_PRODUCTOS.getValue()));
        }

        return value;
    }


}
