/*
 * Generated by JasperReports - 01-03-13 08:53 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class reporteIngresosAlmacen_1362142414402_985975 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_logo = null;
    private JRFillParameter parameter_grupo = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_codigo = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_INGRESOS_ALMACEN_COD_INGRESO_ALMACEN = null;
    private JRFillField field_ORDENES_COMPRA_NRO_ORDEN_COMPRA = null;
    private JRFillField field_MATERIALES_CODIGO_ANTIGUO = null;
    private JRFillField field_UNIDADES_MEDIDA_ABREVIATURA = null;
    private JRFillField field_MATERIALES_NOMBRE_MATERIAL = null;
    private JRFillField field_INGRESOS_ALMACEN_NRO_INGRESO_ALMACEN = null;
    private JRFillField field_INGRESOS_ALMACEN_COD_PROVEEDOR = null;
    private JRFillField field_INGRESOS_ALMACEN_NRO_DOCUMENTO = null;
    private JRFillField field_INGRESOS_ALMACEN_OBS_INGRESO_ALMACEN = null;
    private JRFillField field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO_FISICO = null;
    private JRFillField field_TIPOS_COMPRA_NOMBRE_TIPO_COMPRA = null;
    private JRFillField field_TIPOS_INGRESO_ALMACEN_NOMBRE_TIPO_INGRESO_ALMACEN = null;
    private JRFillField field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO = null;
    private JRFillField field_PROVEEDORES_NOMBRE_PROVEEDOR = null;
    private JRFillField field_INGRESOS_ALMACEN_FECHA_INGRESO_ALMACEN = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_glosa = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_logo = (JRFillParameter)pm.get("logo");
        parameter_grupo = (JRFillParameter)pm.get("grupo");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_codigo = (JRFillParameter)pm.get("codigo");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_INGRESOS_ALMACEN_COD_INGRESO_ALMACEN = (JRFillField)fm.get("INGRESOS_ALMACEN_COD_INGRESO_ALMACEN");
        field_ORDENES_COMPRA_NRO_ORDEN_COMPRA = (JRFillField)fm.get("ORDENES_COMPRA_NRO_ORDEN_COMPRA");
        field_MATERIALES_CODIGO_ANTIGUO = (JRFillField)fm.get("MATERIALES_CODIGO_ANTIGUO");
        field_UNIDADES_MEDIDA_ABREVIATURA = (JRFillField)fm.get("UNIDADES_MEDIDA_ABREVIATURA");
        field_MATERIALES_NOMBRE_MATERIAL = (JRFillField)fm.get("MATERIALES_NOMBRE_MATERIAL");
        field_INGRESOS_ALMACEN_NRO_INGRESO_ALMACEN = (JRFillField)fm.get("INGRESOS_ALMACEN_NRO_INGRESO_ALMACEN");
        field_INGRESOS_ALMACEN_COD_PROVEEDOR = (JRFillField)fm.get("INGRESOS_ALMACEN_COD_PROVEEDOR");
        field_INGRESOS_ALMACEN_NRO_DOCUMENTO = (JRFillField)fm.get("INGRESOS_ALMACEN_NRO_DOCUMENTO");
        field_INGRESOS_ALMACEN_OBS_INGRESO_ALMACEN = (JRFillField)fm.get("INGRESOS_ALMACEN_OBS_INGRESO_ALMACEN");
        field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO_FISICO = (JRFillField)fm.get("INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO_FISICO");
        field_TIPOS_COMPRA_NOMBRE_TIPO_COMPRA = (JRFillField)fm.get("TIPOS_COMPRA_NOMBRE_TIPO_COMPRA");
        field_TIPOS_INGRESO_ALMACEN_NOMBRE_TIPO_INGRESO_ALMACEN = (JRFillField)fm.get("TIPOS_INGRESO_ALMACEN_NOMBRE_TIPO_INGRESO_ALMACEN");
        field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO = (JRFillField)fm.get("INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO");
        field_PROVEEDORES_NOMBRE_PROVEEDOR = (JRFillField)fm.get("PROVEEDORES_NOMBRE_PROVEEDOR");
        field_INGRESOS_ALMACEN_FECHA_INGRESO_ALMACEN = (JRFillField)fm.get("INGRESOS_ALMACEN_FECHA_INGRESO_ALMACEN");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_glosa = (JRFillVariable)vm.get("glosa");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_INGRESOS_ALMACEN_OBS_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_INGRESOS_ALMACEN_NRO_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_INGRESOS_ALMACEN_FECHA_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TIPOS_INGRESO_ALMACEN_NOMBRE_TIPO_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_NOMBRE_PROVEEDOR.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TIPOS_COMPRA_NOMBRE_TIPO_COMPRA.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_NRO_ORDEN_COMPRA.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)field_INGRESOS_ALMACEN_NRO_DOCUMENTO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.io.InputStream)(((java.io.InputStream)parameter_logo.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_grupo.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIALES_CODIGO_ANTIGUO.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIALES_NOMBRE_MATERIAL.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO_FISICO.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_UNIDADES_MEDIDA_ABREVIATURA.getValue()));//$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_INGRESOS_ALMACEN_OBS_INGRESO_ALMACEN.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_INGRESOS_ALMACEN_NRO_INGRESO_ALMACEN.getOldValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_INGRESOS_ALMACEN_FECHA_INGRESO_ALMACEN.getOldValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TIPOS_INGRESO_ALMACEN_NOMBRE_TIPO_INGRESO_ALMACEN.getOldValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_NOMBRE_PROVEEDOR.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TIPOS_COMPRA_NOMBRE_TIPO_COMPRA.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_NRO_ORDEN_COMPRA.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)field_INGRESOS_ALMACEN_NRO_DOCUMENTO.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.io.InputStream)(((java.io.InputStream)parameter_logo.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_grupo.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIALES_CODIGO_ANTIGUO.getOldValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIALES_NOMBRE_MATERIAL.getOldValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO_FISICO.getOldValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_UNIDADES_MEDIDA_ABREVIATURA.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_INGRESOS_ALMACEN_OBS_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_INGRESOS_ALMACEN_NRO_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_INGRESOS_ALMACEN_FECHA_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TIPOS_INGRESO_ALMACEN_NOMBRE_TIPO_INGRESO_ALMACEN.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PROVEEDORES_NOMBRE_PROVEEDOR.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)field_TIPOS_COMPRA_NOMBRE_TIPO_COMPRA.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_ORDENES_COMPRA_NRO_ORDEN_COMPRA.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)field_INGRESOS_ALMACEN_NRO_DOCUMENTO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.io.InputStream)(((java.io.InputStream)parameter_logo.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_grupo.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIALES_CODIGO_ANTIGUO.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)field_MATERIALES_NOMBRE_MATERIAL.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_INGRESOS_ALMACEN_DETALLE_CANT_TOTAL_INGRESO_FISICO.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_UNIDADES_MEDIDA_ABREVIATURA.getValue()));//$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
